baseurl = "http://localhost"
title = "Starter Hugo Base Theme"
uglyurls = false
paginate = 10

[permalinks]
  post = "/:title"

[params]
  Author = "Greg Boggs"
  DateForm = "Jan 2, 2006"
  googleAnalytics = "UA-xxxxxxx-x"
  SyntaxHighlightTheme = "solarized_dark.min.css"
  
#Starter theme specifics
  github = "Greg-Boggs"
  linkedin = "gregoryboggs"
  twitter = "gregory-boggs"

[Indexes]
  categories = "categories"
